# Generated by Django 3.1 on 2022-06-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modified_date',
            new_name='updated_date',
        ),
    ]
